### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'env'

### ISSUE THREAD

**Issue by sofa-potato** [raminaghods/Multi-agent-active-search#2]
D:\python\python.exe F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\main.py 
start process
agents: 1 T=128
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\main.py", line 43, in trials
    beta_hats = Bayesian_optimizer(trl, worker_manager, func_class, options).optimize(max_capital)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\bayesian_optimization.py", line 350, in optimize
    self.optimise_initialise()
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\bayesian_optimization.py", line 289, in optimise_initialise
    self.perform_initial_queries()
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\bayesian_optimization.py", line 148, in perform_initial_queries
    self._dispatch_single_evaluation_to_worker_manager({'beta':self.pre_eval_betas[idx]}, pre_eval=True)#{'X' : X[idx], 'Y' : Y[idx]}) #TODO : modify signature of function to accept a dict of X,Y
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\bayesian_optimization.py", line 264, in _dispatch_single_evaluation_to_worker_manager
    self.worker_manager.dispatch_single_evaluation(self.func_caller, point_dict, qinfo) #TODO : check this function signature - point_dict, qinfo / just point, qinfo ?
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\worker_manager.py", line 236, in dispatch_single_evaluation
    self._dispatch_evaluation(func_caller, point, qinfo, wid, **kwargs)
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\worker_manager.py", line 227, in _dispatch_evaluation
    self.worker_processes[worker_id].start()
  File "D:\python\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\externals\loky\backend\process.py", line 45, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\externals\loky\backend\popen_loky_win32.py", line 73, in __init__
    child_env = {**os.environ, **process_obj.env}
                                 ^^^^^^^^^^^^^^^
AttributeError: 'Process' object has no attribute 'env'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Project_python\RL\Multi-agent-active-search-master\Multi-agent-active-search-master\2D_search\main.py", line 162, in <module>
    result = Parallel(n_jobs=25, prefer='processes')(delayed(trials)(length, width, mu, theta2, lmbd, sigma2, EMitr, k, n, T, agents, mode, err, alpha, schftseed+T*trl) for trl in range(num_trials))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
AttributeError: 'Process' object has no attribute 'env'

进程已结束,退出代码1

**Comment by b18arundhati** [comment]
This error is most likely due to Python versioning issues. You can fix this by replacing the following line of code in worker_manager.py:

`Process(target=target_func, kwargs={'env':os.environ.copy()})`

 instead of 

`Process(target=target_func)`

**Comment by sofa-potato** [comment]
tks very much. But it is also the same problem.
